name: Coverage Reporting

on:
  push:
    branches: [beta]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor == 'SkyhausMedia'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install
        run: npm install

      - name: Run Test & Coverage
        run: npm run test:cov

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
